export const REQ = 'GET_TWITTER_RESPONSE_REQ';
export const RES = 'GET_TWITTER_RESPONSE_RES';
export const FAIL = 'GET_TWITTER_RESPONSE_FAIL';

export const START_POLLING = 'START_POLLING';
export const STOP_POLLING = 'STOP_POLLING';